// Course
export const FETCH_COURSES = "FETCH_COURSES";
export const FETCH_COURSE_DETAIL = "FETCH_COURSE_DETAIL";
export const FETCH_COURSE_BY_ID = "FETCH_COURSE_BY_ID";
export const FETCH_LIST_CATEGORY = "FETCH_LIST_CATEGORY";
export const SEARCH_COURSE = 'SEARCH_COURSE';
export const FETCH_COURSE_SEARCH = 'FETCH_COURSE_SEARCH';
export const SEARCH_NOT_FOUND = 'SEARCH_NOT_FOUND';

//User
export const LOGIN = 'LOGIN';
export const REGISTER = 'REGISTER';
export const UPDATE_USER = 'UPDATE_USER';
export const USER_ADD_COURSE = 'USER_ADD_COURSE';
export const USER_CANCEL_COURSE = 'USER_CANCEL_COURSE';
export const USER_CHECK_COURSE = 'USER_CHECK_COURSE';
export const USER_CHECK_COURSE_APPROVED = 'USER_CHECK_COURSE_APPROVED';


